"""
Cloud-side response generator.

(Internally: SCALPEL Tier 3. Deployed to AWS Lambda. The function name
in AWS is generic — see deploy_cloud.sh.)

DEPLOYMENT:
  1. Zip this file + prompt.txt:  zip cloud.zip lambda_function.py prompt.txt
  2. Run deploy_cloud.sh
"""

import json
import re
import os
import logging
import boto3

REGION = os.environ.get("AWS_REGION", "us-east-1")
MODEL_ID = os.environ.get("BEDROCK_MODEL_ID", "us.anthropic.claude-haiku-4-5-20251001-v1:0")

# Shared secret for caller authentication. Set as Lambda env var SVCD_AUTH_TOKEN.
# The router on the Pi sends X-Svcd-Auth header. Without this, Lambda is
# publicly callable and anyone can drain Bedrock credits.
EXPECTED_AUTH = os.environ.get("SVCD_AUTH_TOKEN", "")

# CloudWatch logger (errors stay server-side, not returned to client)
logger = logging.getLogger()
logger.setLevel(logging.INFO)

bedrock = boto3.client("bedrock-runtime", region_name=REGION)

MAX_COMMAND_LEN = 512
MAX_HISTORY_ITEMS = 10
MAX_MODEL_TOKENS = 350

with open(os.path.join(os.path.dirname(__file__), "prompt.txt")) as f:
    SYSTEM_PROMPT = f.read()


PREAMBLE_RE = re.compile(
    r"^(sure|here(?:'s| is)|i('ll| will| would)|the (output|result)|let me|certainly|of course|absolutely)[,:\s]",
    re.I,
)
MARKDOWN_FENCE = re.compile(r"^```\w*\s*\n?|\n?```\s*$", re.M)
FORBIDDEN_TOKENS = re.compile(
    r"\b(honey ?pot|cowrie|ollama|llm|claude|bedrock|lambda|aws|"
    r"prompt|system prompt|fake|simulat|generated|generated by|"
    r"i (am|cannot|can't)|as an ai|svcd|scalpel)\b",
    re.I,
)
ZERO_WIDTH = re.compile(r"[\u200b\u200c\u200d\u200e\u200f\u2060\ufeff]")


def _check_forbidden(text: str) -> bool:
    """Returns True if text contains forbidden tokens (incl. unicode-bypass attempts)."""
    import unicodedata
    t = ZERO_WIDTH.sub("", text)
    t = unicodedata.normalize("NFKC", t)
    t_compact = re.sub(r"\s+", "", t).lower()
    return bool(FORBIDDEN_TOKENS.search(t) or FORBIDDEN_TOKENS.search(t_compact))


def post_process(text: str) -> str:
    if not text:
        return ""
    text = MARKDOWN_FENCE.sub("", text).strip()
    lines = text.split("\n")
    if lines and PREAMBLE_RE.match(lines[0]):
        lines = lines[1:]
        text = "\n".join(lines).strip()
    if _check_forbidden(text):
        return ""
    return text


def _get_header(event: dict, name: str) -> str:
    """Case-insensitive header lookup (API Gateway and function URLs differ)."""
    headers = event.get("headers", {}) or {}
    for k, v in headers.items():
        if k.lower() == name.lower():
            return v or ""
    return ""


def build_messages(history: list[dict], cmd: str) -> list[dict]:
    messages = []
    for h in history[-5:]:
        messages.append({"role": "user", "content": h.get("cmd", "")})
        messages.append({"role": "assistant", "content": h.get("out", "")})
    messages.append({"role": "user", "content": cmd})
    return messages


def lambda_handler(event, context):
    try:
        # Auth check FIRST. Reject before any expensive Bedrock call.
        if EXPECTED_AUTH:
            provided = _get_header(event, "X-Svcd-Auth")
            if provided != EXPECTED_AUTH:
                logger.warning("auth rejected, header=%s", provided[:8] if provided else "(empty)")
                return {"statusCode": 403, "body": json.dumps({"error": "forbidden"})}

        if isinstance(event.get("body"), str):
            body = json.loads(event["body"])
        else:
            body = event.get("body", event)

        cmd = body.get("command", "").strip()
        history = body.get("history", [])

        if not cmd:
            return {"statusCode": 400, "body": json.dumps({"error": "missing command"})}

        # Bound the request size — reject obviously hostile payloads
        if len(cmd) > MAX_COMMAND_LEN:
            return {"statusCode": 400, "body": json.dumps({"error": "command too long"})}
        if not isinstance(history, list) or len(history) > MAX_HISTORY_ITEMS:
            return {"statusCode": 400, "body": json.dumps({"error": "bad history"})}

        messages = build_messages(history, cmd)

        response = bedrock.invoke_model(
            modelId=MODEL_ID,
            body=json.dumps({
                "anthropic_version": "bedrock-2023-05-31",
                "max_tokens": MAX_MODEL_TOKENS,
                "system": SYSTEM_PROMPT,
                "messages": messages,
                "temperature": 0.2,
            }),
        )

        result = json.loads(response["body"].read())
        text = result["content"][0]["text"]
        cleaned = post_process(text)

        return {
            "statusCode": 200,
            "body": json.dumps({"body": cleaned}),
            "headers": {"Content-Type": "application/json"},
        }

    except Exception as e:
        # Log internally; return generic to caller (don't leak internals).
        logger.exception("handler error")
        return {"statusCode": 500, "body": json.dumps({"body": "", "error": "internal"})}
